### ISSUE TITLE
Archivers selection

### ISSUE THREAD

**Issue by zunbar** [ihavenoface/4chan-x#1]
Creation of a new tab on 4chan X' Settings
An "Archivers" tab.

On the following, a menu is presented in which you can select which archive redirection you will use for each board.

Many boards have more than 1 archiver and this would be useful for those who are not satisfied in having 4chan X decide which to be used. This will increase user's freedom to choose which archiver they want.

Reminders:

1) Always stay up-to-date with all archivers. There are many not well known ones. For example, /e/ archiver.
2) There is not only 404 redirection to deal with, but also the menu's "Archived Post"

Good luck!

**Comment by ihavenoface** [comment]
I decided against a new tab and made it an option list under the sauce tab instead to avoid unnecessary input.

First working version (does not need a refresh, it just werks):
2e07b4e7d7444794e989fcbecc960749fc5cf1c0

**Comment by ihavenoface** [comment]
And c4b23bb49a2e4f1264007e3677f97b9dcd8bbbc1 should pretty much settle it.
@seaweedchan @vampiricwulf @zixaphir, please test this.

As for the placement of the button, I've thought about putting it on the top of the page rather than on the settings to indicate that it will take effect immediately. Y/N?

**Comment by seaweedchan** [comment]
Under the sauce tab is a bit confusing. It has nothing to do with sauce. My first instinct before reading where you put it was to check the Rice tab as that seems to have always been where general miscellaneous options have gone.

Immediately on loading a dead thread I had in my watcher it tried to load archive.foolz.us for /g/ -- which is a problem because obviously they don't archive /g/. Once I opened up the options, viewed the sauce tab, and closed the options, it respected my preference.

**Comment by ihavenoface** [comment]
I'll put it in the rice tab then.

I forgot to do an internal check, one second.

**Comment by ihavenoface** [comment]
~~f04060cd080b90d67f5e563bf8bcc3c7eea792e4~~
~~A bit ugly but all I can come up with atm.~~

0e744cdefb5a7b948b092cb58b61a3e524d774a9

**Comment by vampiricwulf** [comment]
> As for the placement of the button, I've thought about putting it on the top of the page rather than on the settings to indicate that it will take effect immediately. Y/N?

Y (But it should be kept out of the way because it will rarely be altered unless an archive goes down.)

Also, works nicely.

**Comment by ihavenoface** [comment]
> But it should be kept out of the way

What place do you suggest? Imagecontrols perhaps?

On a second thought I believe it is fine with just the current note. As you said people won't change their archivers all too often and this way it won't interfere with existing styles.

**Comment by vampiricwulf** [comment]
Alright, then you should make a note next to the selector that Refreshing isn't necessary to take affect.
Saying "takes effect immediately" isn't nearly as intuitive as saying "No Refresh Needed".

**Comment by ihavenoface** [comment]
> intuitive

We apple now.

**Comment by vampiricwulf** [comment]
>le epick rage guy
~~I-It's not like the word existed and was something people strided for in their products pre-apple. B-Baka!~~
