### ISSUE TITLE
Image embed

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ihavenoface/4chan-x#165]
On some boards there is a strict SFW policy. The only way this content is allowed is by posting links to the relevant content, that has been stated several times. 

So, I thought, if someone would post a link to a .jpg, .png, .jpeg or even .gif, you should be able to embed them in the post, just as much as you can embed YouTube links.

This would lead to people posting their dirty little lewd lolis in link-format and that would then mean there will be less banned people.

Please, make it happen.

**Comment by ihavenoface** [comment]
This would give a certain risk in security, most likely. I would need to stick to a range of imagehosters.

> This would lead to people posting their dirty little lewd lolis in link-format and that would then mean there will be less banned people.

I do not support this.

**Comment by usernamestring** [comment]
What about embedding image links hosted on different 4chan boards?

Like simply linking to

https://images.4chan.org/s/src/1361741801165.jpg

in a SFW board instead of risking a ban

This would be useful when the post has been deleted but the original image and sometimes even the thumbnail are still available.

**Comment by ididntknowicoulddothatXD** [comment]
> that feel when image upload error

See why this would be handy? You reconsider it now?
xddddddddd

**Comment by ihavenoface** [comment]
> xddddddddd

?

**Comment by vampiricwulf** [comment]
I think he exploded. This would be a kinda cool feature, but i don't believe it's worth the coding. Just click the link or remix image hover to show previews of images on link hover. It's pointless to code trivial tasks into complex code. 
This would be abused too easily. :-1:

EDIT:
To clarify, I mean people (who use noface-x) could spam the same image over and over and just turn every reply into  same image spam. Making it into like how image hover works would be pretty cool though.

**Comment by ihavenoface** [comment]
> Making it into like how image hover works would be pretty cool though.

Guess I'm doing this on demand like the Youtube stuff.

**Comment by vampiricwulf** [comment]
In case I was being misunderstood: I'd like to clarify that I disagreed that the feature should be added, I was just stating an alternative that is better than the original proposed feature. (imho)
I disagreed because I find it useless, it's a link, how hard is it to click it? Your hand is already on your mouse/touchpad while you're scrolling.

**Comment by ihavenoface** [comment]
Disregard what stood here.

> Your hand is already on your mouse/touchpad while you're scrolling. 

Following that logic 4chan x shouldn't exist in the first place. I mean, how hard must it be to press F5?

**Comment by vampiricwulf** [comment]
Reloading the entire page is slow and inefficient, 4chanx makes the process of streamline and less wasteful. 4chanx (going from vanilla 4chan) also adds more features than that, QR, image expansion, and custom keybinds are just a small bit to mention.
My thought process was "is 50 lines of code worth one click? Nothing is really much faster. What's the gain? The only time it would be streamlined is if you use prefetching and it also prefetched linked images. Since that's not the case, nothing is really to be gained."

**Comment by ihavenoface** [comment]
It still convenient, probably.
What do? Flip a coin?

**Comment by vampiricwulf** [comment]
If you believe it's convenient, then do it, I'm sure it'd attract more users from other scripts to use this instead.

**Comment by ihavenoface** [comment]
Embedding supports imgur.com now. This should cover most external images.
