### ISSUE TITLE
Collaborate with seaweed and zixaphir on their fork

### ISSUE THREAD

**Issue by TetsuoAm** [ihavenoface/4chan-x#219]
Currently their fork contains _everything_ your v2 fork did, has a lot of great new features, has a lot done that you still have open in your issues now, has a lot of bug fixes for things that aren't even reported on your 4chan X fork yet like the fact that your Check for Updates option points to a URL that isn't there, and has an install page instead of a blank page with a couple links.

They are both [wanting to work with you](https://github.com/seaweedchan/4chan-x/issues/39#issuecomment-17189638) and [seaweed wants to apologize](https://github.com/seaweedchan/4chan-x/issues/39#issuecomment-17191372) for whatever started your drama in the first place.

You joining with them would not only allow you to work on new things by taking away all the unnecessary work you still need to do for your v3 fork, but it would also make things great for both their fork and all non-Mayhem users.

The only downside to joining their project instead would be that you couldn't have the self esteem boost from people using your fork specifically. Please don't let pride or dignity get in the way of unifying for one great userscript.

**Comment by lucy** [comment]
:-1: 
(I'm severely biased, though)

**Comment by zixaphir** [comment]
:+1:
I'd like to point out that I don't particularly mind you just pulling in our features and bugfixes to your fork. In fact, I feel that collaboration between our two repos could be possible without having to sacrifice having your own "flavor" of 4chan X, that you distribute with your custom changes and features that might not feel so at home in the fork @seaweedchan and I are maintaining.

In fact, it's arguable that Appchan X is my own personal flavor of 4chan X and @seaweedchan's repo is his, as I don't necessarily always pull in or agree with his changes.

In the end, though, I just want to see users have better options than Mayhem X, so any ulterior motivations you might suspect me of are on the table. And if Mayhem X becomes a better script because of this, I am _also_ fine with that.

**Comment by ihavenoface** [comment]
> has a regularly maintained Chrome extension on the Chrome web store instead of a CRX

So does mine.

**Comment by TetsuoAm** [comment]
> So does mine.

Okay, updated. Everything else still remains true.

> ihavenoface closed the issue 5 hours ago

Why?

**Comment by ihavenoface** [comment]
> Why?

Because I do not agree with you? See 

> that you distribute with your custom changes and features that might not feel so at home in the fork @seaweedchan and I are maintaining.

for reference.

**Comment by TetsuoAm** [comment]
And yet, here you are with just a fork of Mayhem's with a couple very small changes, still missing many of the features of your old version, serving only to contribute to the fragmentation of 4chan X forks.

You have no features or changes that wouldn't feel at home in their fork because you have no features or changes that they haven't already implemented.

You're losing users fast and I don't see how you find that acceptable.

**Comment by ihavenoface** [comment]
> serving only to contribute to the fragmentation of 4chan X forks.

Excuse me?

Anyway, I said it in the past and I'm going to say it again:
This here isn't meant to be a race for who-has-the-most-features, it's to have a script similar to the one provided in mayhems branch with a few things added where and when I see fit, but if I felt the urge to work together with the two and leave my little island be I would have done so.

If you can't cope with it you and everyone else has the ability to choose whichever fork he/she thinks is best. Choice is not a bad thing.

**Comment by TetsuoAm** [comment]
> Excuse me?

You know, the main complaint people have on 4chan about 4chan X forks -- that there's so many of them. You have an established user base that has come from the former time when you had the only other main 4chan X fork, but you're just being unfair to that user base by working at a pace of 5 commits a week and not contributing to the current only non-Mayhem fork that is actually worked on at a decent pace. You either have the time and passion to run your own fork on your own, or you don't. You clearly don't.

> This here isn't meant to be a race for who-has-the-most-features

No one said it has to be a race, but you shouldn't have released your 4chan X v3 fork in the first place if it was a step backwards from your v2 fork which right now it 100% is. It's unfinished. You have catching up to do. That's a fact.

> it's to have a script similar to the one provided in mayhems branch with a few things added

And yet apparently you went from many things to very few things and found that acceptable?

> when I see fit

Which is rarely.

> if I felt the urge to work together with the two and leave my little island be I would have done so

Well duh. The point of me making this issue was to open this up for discussion so you could weigh the pros and cons and make an informed decision. Instead you're doing exactly what I said not to -- saying no purely out of pride.

> Choice is not a bad thing.

You're moving the goal post. You can either actually finish your fork, or contribute to a fork that actually is finished. Not choosing one of those IS a bad thing, and a slap in the face to all of your users.

**Comment by ihavenoface** [comment]
> and make an informed decision

And still none of the points you're making is news.

**Comment by TetsuoAm** [comment]
> And still none of the points you're making is news.

Then you acknowledge all of the problems your fork has, the fact that you're slapping your users in the face, and the fact that you're imposing on yourself tons of unnecessary work?

You're sounding a bit like Mayhem.

**Comment by zixaphir** [comment]
I didn't mean for this to become an aggressive issue. I'm not all innocent in this mess, but I guarantee you that there are things in our fork that would be at home in yours, and I don't want to feel like an ass every time I pull one of your features because you don't want anything to do with ours.

**Comment by vampiricwulf** [comment]
Oh geez, I didn't think this would cause so much conflict. I am in agreement that you should get involved with seaweed's fork, but since there's such a big dispute; maybe it's best everyone just sticks where they are right now. Maybe in the future everyone will be a bit more compliant and friendly, but now it seems to have turned into a bashfest. I thought everyone would be friendly since they were working for a common goal, but okay.

I really hope you guys can be on friendlier terms on the future, and as always, I'm grateful for everything everyone has done.
