### ISSUE TITLE
Can't put Twitter link on Custom Board Navigation.

### ISSUE THREAD

**Issue by usernamestring** [ihavenoface/4chan-x#232]
I tried putting '@' or 'Twitter' but it appears as text, not link.
Also I'd like to know if the 'remember sage' option will be back.
Also I'd like to know if filters will work on Catalog pages in future updates.
Thank you.

**Comment by ihavenoface** [comment]
> I tried putting '@' or 'Twitter' but it appears as text, not link.

Looks like this bug is present in upstream. Will look into it.

> Also I'd like to know if the 'remember sage' option will be back.

I gave an answer about that [here](https://github.com/ihavenoface/4chan-x/issues/200#issuecomment-17303101).

> Also I'd like to know if filters will work on Catalog pages in future updates.

afaik this was integrated at some point. No idea where that went.

On a different note - please update https://github.com/ihavenoface/4chan-x/issues/76 with info that is still an issue after 6 months.
