### ISSUE TITLE
Linikfy common bypass syntax

### ISSUE THREAD

**Issue by ldgbc** [ihavenoface/4chan-x#40]
Linkify 'text' that is purposely broken to bypass filter/avoid auto ban.

For example;

"http://github(dot)com"
or
"http://github.com(slash)ihavenoface"

Only common one though... I assume it would be hard for more encrypted link

**Comment by ihavenoface** [comment]
Define some more "common" links and I'll put that in.

**Comment by vampiricwulf** [comment]
`(space)` I believe is used sometimes.

**Comment by ihavenoface** [comment]
Honestly I've never seen that before. More like DOT. Truth is that there are too much common variations this would actually be useless.

**Comment by vampiricwulf** [comment]
I've seen it only in very rare cases, but not on 4chan. It'd be cool for this to be included, but on 4chan everyone knows that the way to get around it is jsut blank spoiler tags or breaking it off onto the next line.

The spoiler part still needs to be fixed btw, and also as said in the other issue, I can't get yours to work at all, only the original 4chan linkify script works. (blank spoilers doesn't work on the 4chan linkify either, only in the script some random person put together.)

**Comment by ihavenoface** [comment]
Then again, leave me some more examples to work with if you want it implemented.

As it looks the spoiler issue occurs because Linkify simply doesn't watch for them when parsing the comment section. I'm sure @zixaphir is able to turn it in the right direction though.

> I can't get yours to work at all, only the original 4chan linkify script works.

A few console outputs or something would be helpful then. I'm glad to be helpful but you can't expect from me to analyze two different scripts in order to fix something I haven't even touched yet.

> Also, it's not working for me. At all. Know any reason why?

I do not use Mac OS, sorry. Works fine here on both Looniks and Windows.

**Comment by vampiricwulf** [comment]
Is there a way to contact you for IMing? IRC/Skype/etc. I'd rather do instant messaging than create the largest issue in existence.

> A few console outputs or something would be helpful then.

If only it outputted any.

**Comment by zixaphir** [comment]
I do not have a mac computer to test keybinds on. Shift+Ctrl+Click was what the script I based my linkifier on used. If you could provide a safe mac combination, I could write it in.

As for common wordfilter and link bypass with (DOT) and the like, I do not feel comfortable trying to write a catch-all for all of those. My script searches for links that are properly formed. I only wrote in a spoiler by-pass because it still displays on-screen as a legitimate link broken only by formatting

**Comment by ihavenoface** [comment]
> I do not feel comfortable trying to write a catch-all for all of those.

I completely agree with this statement.

> Is there a way to contact you for IMing? IRC/Skype/etc.

MSN - > noface@outlook.com

Closing this now.
