### ISSUE TITLE
Images+Thumbnails 404

### ISSUE THREAD

**Issue by ghost** [ihavenoface/4chan-x#45]
The newer version of 4chan X has this odd issue where all images (at least in /v/ and /g/) go to 
" http://boards.4chan.org/[BOARD]/src/[IMAGE] " instead of img.4chan.org or whatever it was called.

**Comment by ghost** [comment]
A stranger note:
Images on the main board ( say, just like boards.4chan.org/[BOARD] ) proccess the images and thumbnails correctly.

**Comment by seaweedchan** [comment]
Not a 4chan X issue.

**Comment by ghost** [comment]
Huh, odd. Okay then.

**Comment by ihavenoface** [comment]
@seaweedchan - care to give a citation on that?

**Comment by vampiricwulf** [comment]
4chan went to shit last night and all full sized images (that weren't fetched) linked to boards.\* instead of images.\* so all that would load on page load were just the thumbnails and images couldn't be expanded as they would just 404 due to bad url.
As seaweed says, this isn't 4chanx's fault, hell if anything 4chanx made it bareable since fetched images worked gracefully.
