### ISSUE TITLE
Positioning issue

### ISSUE THREAD

**Issue by seaweedchan** [ihavenoface/4chan-x#46]
When resizing window to the left, the updater/stats retain their positions. When resizing to the right, their positions don't change for the window resize and instead stay where they were on the page. This obviously messes with userstyles with fixed elements, specifically for me, OneeChan as of 4.3.3 (released the stats and updaters so users can reposition them).

I call for this either to be changed somehow so that when the updater is on the right side of the window it moves dynamically, or for there to be an option in the updater called something along the lines of "Lock/Unlock Thread Updater/Stats"

**Comment by ihavenoface** [comment]
_When resizing window to the left, the updater/stats, only when have been taken from their original position (in the corners), retain their positions._

Thanks for reporting.

**Comment by ihavenoface** [comment]
Alright so I spend some quality time with to play around with this and observed the following things:

```
dragstart: function(e) {
  var el, rect;
  e.preventDefault();
  UI.el = el = this.parentNode;
  d.addEventListener('mousemove', UI.drag, false);
  d.addEventListener('mouseup', UI.dragend, false);
  rect = el.getBoundingClientRect();
  UI.dx = e.clientX - rect.left;
  UI.dy = e.clientY - rect.top;
  UI.width = d.documentElement.clientWidth - rect.width;
  return UI.height = d.documentElement.clientHeight - rect.height;
},
drag: function(e) {
  var left, style, top;
  left = e.clientX - UI.dx;
  top = e.clientY - UI.dy;
  left = left < 10 ? '0px' : UI.width - left < 10 ? null : left + 'px';
  top = top < 10 ? '0px' : UI.height - top < 10 ? null : top + 'px';
  style = UI.el.style;
  style.left = left;
  style.top = top;
  style.right = left === null ? '0px' : null;
  return style.bottom = top === null ? '0px' : null;
},
```

Looking at this tells me that every element gets calculated over the left or top value for reference. If I don't want to fuck this up completely I'll have to do right and bottom completely new meaning I'd have to change every element that relies on `UI.drag()` or `UI.dragstart()` because, according to the LocalStorage, the stuff doesn't even get passed in the first place.

No idea when I will be able to do this proper but this definitely is more than a one-liner.

**Comment by seaweedchan** [comment]
Eek.

At least its a low priority issue.

**Comment by zixaphir** [comment]
For reference, if you position from the opposite corners, it's just going to get stuck overflowing the other way. The only way to really do this is to write it in such a way that the positions are rechecked on DOM insertion to make sure their positions are not larger than the available space.
