### ISSUE TITLE
Chromium does not save name preferences in a dropdown

### ISSUE THREAD

**Issue by seaweedchan** [ihavenoface/4chan-x#60]
Oddly enough this only happens with 4chan X and nothing else. Any idea?

Its happened to me for a while now. I pointed it out to Mayhem once and got shrugged off.

As in I want it to save past entries for me to select by focusing the input field and using the down arrow key. It acts like nothing is saved at all. Firefox works with it fine.

**Comment by ihavenoface** [comment]
> namefield

![](http://i.imagebanana.com/img/qm29hqb7/1339511173820.jpg)

I can look for it though.

**Comment by seaweedchan** [comment]
thx qt

**Comment by ihavenoface** [comment]
Short story short - I don't know and since I use the namefield next to never please excuse that I don't want to spend more than 20 minutes on the subject. Should I start working on #2 this might be fixed with a dropdown for names used on each board anyway, no idea what my possibilities will be in this regard.
