### ISSUE TITLE
Title of fileSelect gets openend when file selector is already open.

### ISSUE THREAD

**Issue by ihavenoface** [ihavenoface/4chan-x#67]

**Comment by seaweedchan** [comment]
Perhaps redesign it the way AppChan X does -- Zixaphir just uses a span with text inside of it that disappears and is replaced by just the filename with no path.

He has a title that appears on hover as well, but I can confirm you can just leave that title out.

This might be an annoying solution since it might break style compatibility with Mayhem X, but its still an idea.
