### ISSUE TITLE
Auto-wrap text

### ISSUE THREAD

**Issue by emoloney** [ihavenoface/4chan-x#72]
It would be nice if we could auto-wrap text to stop the thread watcher from covering text at the top of the page.

http://puu.sh/1w0pP

Thank you.

**Comment by ihavenoface** [comment]
The thread watcher isn't defined as inline element so this won't be possible.
Well it would be but this would require to make almost every element on the page aware of the watcher and that's too much work and effort for nothing.
Since you're using OneeChan (or so it seems) anyway you can always activate the persistent sidebar and lock the watcher in place.
